Feature/2434 rejected ur
DOAJ/doaj pull request #1859
Opened 2021-03-01 16:48 UTC by richard-jones

Not ready for merge yet, but ready for review

2021-03-03 09:06 UTC, amdomanska requested changes

2021-03-03 09:06 UTC, amdomanska commented on portality/bll/services/application.py
> +            raise exceptions.IllegalStatusException(message="The application {id} is in 'rejected' state; place it into the correct new state before calling unreject_application".format(id=applicatio
There are also a few below.

2021-03-05 09:09 UTC, richard-jones commented on portality/bll/services/application.py
> +        if rjid:
no, if there is no related journal the "unreject" process is a noop essentially

2021-03-05 11:32 UTC, Steven-Eardley approved these changes

2021-03-05 11:32 UTC, Steven-Eardley commented on portality/bll/exceptions.py
> +    def __init__(self, message=None):
An exception with a message param is pretty retro in python3, but I'm aware this exists in plenty of other places in the DOAJ codebase.

2021-03-11 11:41 UTC, merged