Correct subject of email for update request
DOAJ/doaj pull request #1895
Opened 2021-04-28 16:17 UTC by amdomanska

patch for: https://github.com/DOAJ/doajPM/issues/2570

2021-04-28 16:57 UTC, amdomanska commented
Tested with Mailtrap:

![Screenshot from 2021-04-28 17-55-18](https://user-images.githubusercontent.com/8298769/116443082-1f88ba80-a84b-11eb-803f-f8375a794a09.png)

2021-04-29 04:58 UTC, richard-jones approved these changes

2021-04-29 08:15 UTC, Steven-Eardley requested changes
This causes a genuine test failure - we need some updates in doajtest/unit/application_processors/test_application_processor_emails.py

The first test needs updating:
* It uses an update request fixture where it should be a new application
* It doesn't check both update requests and new applications

I assume the fixture was repurposed after this test was written, since it predates update requests.

2021-04-29 08:15 UTC, Steven-Eardley commented on portality/formcontext/formcontext.py
> +        if update_request:
We don't use formcontext.py any more, it will be removed - changes here aren't needed.

2021-04-29 15:41 UTC, amdomanska commented on doajtest/unit/application_processors/test_application_processor_emails.py
> +        publisher_subject = 'update request accepted'
test updated

2021-05-06 16:28 UTC, closed without merging