support html tags for crossref upload
DOAJ/doaj pull request #1928
Opened 2021-06-18 14:38 UTC by amdomanska

2021-06-22 08:24 UTC, richard-jones requested changes
There's a change to the BLL method signatures, which may break other things, and will probably break tests, and we should look at whether it's necessary and if so if there's a better way to approach it.

2021-06-22 08:24 UTC, richard-jones commented on doajtest/unit/test_tasks_ingestCrossrefArticles.py
> +    def test_51_html_tags_in_title_attr(self):
Not that it matters terribly, but your test numbers are both `51`

2021-06-22 08:24 UTC, richard-jones commented on portality/crosswalks/article_crossref_xml.py
> +#     return None
Dead code cleanup

2021-06-22 08:24 UTC, richard-jones commented on portality/tasks/ingestarticles.py
> +                result, ids = articleService.batch_create_articles(articles, account, add_journal_info=True)
The article IDs are surely added to each article once they are saved?  You don't need to return the ids, I don't think.  If we do have to change the return type of the `batch_create_articles` and the `create_articles` methods, then we should talk about it in a bit more detail first, as the aim of the BLL is to provide a clean, consistent interface to the core, and this response type change feels hacked in.

2021-06-22 08:24 UTC, richard-jones commented on portality/bll/services/article.py
> +                result, id = self.create_article(article, account,
See comment on below about the `batch_create_article` method.  I don't think this change is necessary, but if it is I'd want to talk through the implementation of a change to the BLL's method signature, as I don't think this is the cleanest approach.

2021-07-27 09:08 UTC, merged

2021-10-05 13:49 UTC, dommitchell commented
@amdomanska @richard-jones can I just confirm that what we are seeing here now is as expected? https://bit.ly/3mjLnrm

with italics tags appearing in the titles?