Feature/clockss upload
DOAJ/doaj pull request #1959
Opened 2021-08-04 07:13 UTC by RK206

Merging recent changes for Preservation upload

2021-08-14 14:02 UTC, Steven-Eardley requested changes
I may have further feedback on structure once i've seen this all together in the feature branch - currently I am wondering whether Preserve, Preservation and PreservationPackage might be structured better. For now, there's smaller changes commented in this PR.

2021-08-16 11:44 UTC, RK206 commented on portality/models/preservation.py
> +    @status.setter
Good catch. Updated

2021-08-16 11:45 UTC, RK206 commented on portality/tasks/preservation.py
> +from portality.models import Article, BackgroundJob, Preserve
Yes will find a better  name for it

2021-08-16 11:45 UTC, RK206 commented on portality/tasks/preservation.py
>          :param sha256: sha256sum value
Added doc string

2021-08-16 11:49 UTC, RK206 commented on portality/tasks/preservation.py
> +            os.makedirs(self.__local_dir, exist_ok=True)
No it is not  a problem if folder exist. This is to make sure folder iis available and create if not available

2021-08-25 03:10 UTC, RK206 commented
Changes are committed. Ready for review

2021-08-25 14:36 UTC, richard-jones requested changes
One really minor thing.  Otherwise, I haven't tested this in detail, but I will do that soon.

2021-08-25 14:36 UTC, richard-jones commented on portality/tasks/preservation.py
> +        dir_name = "rama-2021-07-28-13-05-27" #username + "-" + created_time
looks like some testing code slipping through here

2021-09-13 05:49 UTC, richard-jones reviewed
There seem to be some changes in this PR that come from the background jobs refactoring that I did a while back.  Can we just check what's going on here, to make sure nothing is messed up with the PR?  In particular look at the changes in `portality/models/background.py`

2021-09-13 11:27 UTC, RK206 commented
@richard-jones  I fixed merge conflicts and clockss_main got merged into clockss_upload when I commit the changes.
I tested clockss_upload and everything looks fine

2021-09-14 14:11 UTC, merged