OG URLs need to be absolute to be displayed
DOAJ/doaj pull request #2055
Opened 2022-02-08 12:18 UTC by sssoz

See DOAJ/doajPM#3227

2022-02-10 16:48 UTC, richard-jones approved these changes

2022-02-14 14:45 UTC, Steven-Eardley requested changes
these being relative paths was an indication that the variable wasn't being passed into a template, the fix is to pass it in with     

```
render_template('doaj/index.html', news=news, recent_journals=recent_journals, base_url=app.config.get('BASE_URL'))
```

2022-02-14 15:35 UTC, closed without merging

2022-02-14 15:35 UTC, sssoz commented
Fixing `base_url` on another branch instead, as suggested by @Steven-Eardley

2022-02-14 15:57 UTC, sssoz commented
See new PR for this here: https://github.com/DOAJ/doaj/pull/2059