Feature/3256 es type mismatch
DOAJ/doaj pull request #2069
Opened 2022-03-23 14:05 UTC by amdomanska

issue: https://github.com/DOAJ/doajPM/issues/3256
steps completed: https://github.com/DOAJ/doajPM/issues/3256#issuecomment-1074993641

Migration needed

2022-03-23 15:12 UTC, richard-jones requested changes

2022-03-23 15:12 UTC, richard-jones commented on portality/api/current/data_objects/article.py
> +                del dat["admin"]["es_type"]
This isn't where `es_type` is, its just in the root of the object

2022-03-23 21:04 UTC, richard-jones approved these changes

2022-04-01 15:18 UTC, richard-jones approved these changes

2022-04-12 08:41 UTC, Steven-Eardley approved these changes

2022-04-12 08:41 UTC, merged