Feature/consumer publisher created
DOAJ/doaj pull request #2080
Opened 2022-04-21 07:30 UTC by RK206

2022-04-24 16:09 UTC, richard-jones requested changes
A bit of a mix up here on the event type.  I know that Rama is away so I may come back and fix this one up myself shortly

2022-04-24 16:09 UTC, richard-jones commented on cms/data/notifications.yml
> +    This is an automated message."
No need to add the sign off here, that's added by the notification emailer.

As an aside, we may want to look at shortening the text here to feel more like a notification, will raise that separately.

2022-04-24 16:09 UTC, richard-jones commented on cms/data/notifications.yml
> +    "Directory of Open Access Journals - your application to DOAJ has been received"
No need to prefix with Directory of Open Access Journals - this is done by the notifier

2022-04-24 16:09 UTC, richard-jones commented on portality/constants.py
> +    APPLICATION_STATUS_CREATED
Not a new status, so shouldn't be here

2022-04-24 16:09 UTC, richard-jones commented on portality/constants.py
> +APPLICATION_STATUS_CREATED = "created"
This isn't a new status.  I think the confusion here is that this notification has been wired to a "created" status, when in fact what we want is an event for the creation of a new application.  The initial application status will be "pending" or whatever it is set to.

2022-04-24 16:09 UTC, richard-jones commented on portality/events/consumers/application_publisher_created_notify.py
> +               event.context.get("status") == constants.APPLICATION_STATUS_CREATED
I think we should be cosnuming an `application:created` event here

2022-04-24 16:09 UTC, richard-jones commented on portality/forms/application_processors.py
> +        }))
This should be

```
eventsSvc.trigger(models.Event(constants.EVENT_APPLICATION_CREATE, current_user.id, {
            "application": self.target.data
}))
```

2022-04-25 19:48 UTC, richard-jones commented
I have now made these changes, so @Steven-Eardley @amdomanska perhaps you could give it a review now?

2022-05-02 22:15 UTC, Steven-Eardley approved these changes

2022-05-02 22:22 UTC, merged