Feature/3245 ur app tabs
DOAJ/doaj pull request #2084
Opened 2022-04-27 13:33 UTC by amdomanska

https://github.com/DOAJ/doajPM/issues/3245

Migration rules:

    Look for applications which are rejected
    If they have a related_journal then they must be an update request

2022-05-01 10:16 UTC, richard-jones requested changes
Minor change to improve performance and unnecessary work on the index, otherwise good to go

2022-05-01 10:16 UTC, richard-jones commented on portality/migrate/3245_ur_vs_app/operations.py
> +    if application.related_journal:
I'd add a `and not application.application_type == constants.APPLICATION_TYPE_UPDATE_REQUEST` check here too, just to make sure we're not calling save on applications that don't need it

2022-05-13 14:41 UTC, Steven-Eardley approved these changes

2022-05-23 11:13 UTC, richard-jones approved these changes

2022-05-31 09:09 UTC, merged