Feature/application publisher accepted rejected notifications
DOAJ/doaj pull request #2087
Opened 2022-04-29 10:42 UTC by amdomanska

TODO: email text is invalid (especially urls!)

application:publisher:accepted:notify
Create a notification for the owner of the journal when the status is switched to Accepted

application:publisher:rejected:notify
Create a notification to the publisher when the application is rejected

https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit#gid=1277065021 (rows 12 & 14)

2022-05-01 10:51 UTC, richard-jones reviewed
It turns out that two of the consumers turned out to be the same, and we may have both implemeted the same thing.  I think we'll need to unpick that one together during the week next week.

2022-05-03 16:50 UTC, amdomanska commented on portality/bll/services/events.py
> -        ApplicationManedReadyNotify
This is duplicated with line 21

2022-05-03 16:50 UTC, amdomanska commented on portality/bll/services/events.py
> -        ApplicationManedReadyNotify
This is duplicated with line 21

2022-05-05 13:41 UTC, richard-jones requested changes

2022-05-05 13:41 UTC, richard-jones commented on doajtest/unit/event_consumers/test_application_publisher_rejected_notify.py
> +        event = models.Event(constants.EVENT_APPLICATION_ASSED_ASSIGNED, context={"application": {"key" : "value"}})
Technically the wrong event, though it doesn't actually impact on the test execution and outcome here

2022-05-05 13:41 UTC, richard-jones commented on portality/forms/application_processors.py
> +                        }))
This trigger isn't required here, as the application status change event is triggered at the end of the function anyway

2022-05-05 13:41 UTC, richard-jones commented on portality/view/admin.py
> +                "new_status": self.target.application_status
self.target and self.source don't exist here, right?  You'll need to pass `application.data` and then get the before application_status from the application when you first load it.  Then the new status is obviously rejected, which we can take from the `constants` module

2022-05-10 08:24 UTC, merged