add basic search view for notifications
DOAJ/doaj pull request #2096
Opened 2022-05-09 21:35 UTC by richard-jones

2022-07-04 15:37 UTC, philipkcl requested changes

2022-08-03 10:36 UTC, richard-jones commented on portality/lib/edges.py
>      return parse.quote_plus(json.dumps(query))
This is fixed on `master`, so the fix should bubble up during merge

2022-08-10 13:46 UTC, philipkcl reviewed
one comment for `url_for`

2022-08-23 12:05 UTC, richard-jones commented on portality/events/consumers/application_publisher_accepted_notify.py
> +            faq_url=url_for("doaj.faq", _external=True)
Yes, good spot, I'll fix that one too

2022-08-24 10:41 UTC, richard-jones commented on portality/events/consumers/application_publisher_accepted_notify.py
> +            faq_url=url_for("doaj.faq", _external=True)
Fixed

2022-08-24 10:42 UTC, richard-jones commented
I have fixed the issues identified and also merged up from develop (via feature/editoria-workflow--stage2)

2022-08-24 11:38 UTC, amdomanska approved these changes
I couldn't generate notifications but the button looks slightly out of line, is that intentional?

![image](https://user-images.githubusercontent.com/8298769/186409041-82d2be40-1d60-47cc-9296-5dbb33faa0d2.png)


Other than that looks fine to me.

2022-09-14 18:58 UTC, Steven-Eardley approved these changes
This is superb

2022-09-14 19:02 UTC, merged