Wrong message when file with no issn uploaded
DOAJ/doaj pull request #2143
Opened 2022-08-26 12:44 UTC by amdomanska

Wrong message when file with no issn uploaded

*Please don't delete any sections when completing this PR template; instead enter **N/A** for checkboxes or sections which are not applicable, unless otherwise stated below*

[See #3347](https://github.com/DOAJ/doajPM/issues/3347)

So far when article was not acceptable (no DOI, no fulltext and/or no issns) generic text has been provided to the user. Additionally no issns has been treated the same as identical issns (`None == None = True`). The specific check for no issns has been added and instead of generic string the exact exception message is provided to the UI.

## Categorisation

This PR...
- [ ] **N/A** has scripts to run
- [ ] **N/A** has migrations to run
- [ ] **N/A** adds new infrastructure
- [ ] **N/A** changes the CI pipeline
- [x] affects the public site
- [ ] **N/A** affects the editorial area
- [ ] **N/A** affects the publisher area

## Basic PR Checklist

- [ ] **N/A** FeatureMap annotations have been added
- [x] Unit tests have been added/modified
- [ ] **N/A** Functional tests have been added/modified
- [x] Code has been run manually in development, and functional tests followed locally
- [x] No deprecated methods are used
- [x] No magic strings/numbers - all strings are in `constants` or `messages` files
- [ ] **N/A** ES queries are wrapped in a Query object rather than inlined in the code
- [ ] **N/A** Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- [ ] **N/A** If needed, migration has been created and tested locally
- [ ] **N/A** Release sheet has been created, and completed as far as is possible https://docs.google.com/spreadsheets/d/1Bqx23J1MwXzjrmAygbqlU3YHxN1Wf7zkkRv14eTVLZQ/edit
- [ ] **N/A** Documentation updates - if needed - have been identified and prepared for inclusion into main documentation (e.g. added and highlighted/commented as appropriate to this PR)
    - [ ] **N/A** Core model documentation: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
    - [ ] **N/A** Events and consumers documentation: https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit
- [x] There has been a recent merge up from `develop` (or other base branch)

## Testing

**N/A** 

## Deployment

**N/A** 

### Configuration changes

**N/A** 

### Scripts

**N/A** 

### Migrations

**N/A** 

### Monitoring

**N/A** 

### New Infrastructure

**N/A** 

### Continuous Integration

**N/A**

2022-08-29 11:52 UTC, Steven-Eardley approved these changes

2022-08-31 15:03 UTC, philipkcl reviewed
very minor comment. consider remove duplicate comment.

2022-09-08 09:53 UTC, richard-jones requested changes
I think the PR looks fine, though it needs to go up onto test I think, for a bit of functional testing.

We should add a functional test for the No ISSNs case and ask the DOAJ team to run it on the test server.

The tests should be added in https://docs.google.com/spreadsheets/d/1oOSC591NGA-05tXqTpwlYSelyYTORtorxU79sqN_xwE/edit#gid=0

For the Crossref 5.3.1 functional tests, these should be created in https://github.com/DOAJ/doaj/blob/develop/doajtest/testbook/article_xml_upload/crossref-5.3.1.yml first, following the pattern of the other tests, and then duplicated into the spreadsheet (for the time being, while we migrate to this new approach).

You can compile the new style functional tests by installing and running https://github.com/CottageLabs/testbook and then you can download the test suite as a csv and copy over the new test into the spreadsheet (I'm working on a mechanism to do this automatically, but it is not ready yet)

2022-09-16 12:54 UTC, amdomanska commented
@richard-jones I've updated the functional tests - for DOAJ and Crossref 4.4.2 directly in the spreadsheet, for Crossref 5.3.1 with testbook. I also merged in the latest develop - it had conflict in the Crossref 5.3.1 area, so it would be useful to test it with that in mind.

2022-11-22 17:00 UTC, merged