Remove an unnecessary test expression
DOAJ/doaj pull request #2195
Opened 2023-01-18 17:52 UTC by openrefactory

In file: article_form.py, method: form2obj, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not match with anything else. As a result, the identity check will have a logical short circuit. The first part of the test expression already tests for it. The second part is unnecessary.

I suggested that the logical operation should be reviewed.

2023-01-20 15:50 UTC, Steven-Eardley requested changes
This is an extremely minor thing, but it's correct that there's no effect:

```pycon
>>> k = []
>>> k is []
False
>>> k is k
True
>>> [] is []
False
```

However, I suggest we change it to the intended check rather than removing it altogether.

2023-01-20 15:50 UTC, Steven-Eardley commented on portality/crosswalks/article_form.py
> +        if keywords is not None:
```suggestion
        if keywords is not None and len(keywords) > 0:
```

It's true that the expression didn't have the required effect, but it's better to replace with a working check than remove it entirely.

2023-01-23 18:55 UTC, openrefactory commented
Modified based on suggestion.

2023-01-24 15:43 UTC, Steven-Eardley approved these changes

2023-01-24 15:43 UTC, merged