Feature/3424 archiving project
DOAJ/doaj pull request #2207
Opened 2023-02-03 10:40 UTC by RK206

# Upload packages individually

*Please don't delete any sections when completing this PR template; instead enter **N/A** for checkboxes or sections which are not applicable, unless otherwise stated below*

See # https://github.com/DOAJ/doajPM/issues/3424

Describe the scope/purpose of the PR here in as much detail as you like

## Categorisation

This PR...
- [ ] has scripts to run
- [ ] has migrations to run
- [ ] adds new infrastructure
- [ ] changes the CI pipeline
- [ ] affects the public site
- [ ] affects the editorial area
- [ ] affects the publisher area
- [ ] affects the monitoring

## Basic PR Checklist

- [ ] FeatureMap annotations have been added
- [ ] Unit tests have been added/modified
- [ ] Functional tests have been added/modified
- [ ] Code has been run manually in development, and functional tests followed locally
- [ ] No deprecated methods are used
- [ ] No magic strings/numbers - all strings are in `constants` or `messages` files
- [ ] ES queries are wrapped in a Query object rather than inlined in the code
- [ ] Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- [ ] If needed, migration has been created and tested locally
- [ ] Have you done a recent merge up from `develop`
- [ ] Cleaned up commented out code, etc
- [ ] Release sheet has been created, and completed as far as is possible https://docs.google.com/spreadsheets/d/1Bqx23J1MwXzjrmAygbqlU3YHxN1Wf7zkkRv14eTVLZQ/edit
- [ ] Documentation updates - if needed - have been identified and prepared for inclusion into main documentation (e.g. added and highlighted/commented as appropriate to this PR)
    - [ ] Core model documentation: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
    - [ ] Events and consumers documentation: https://docs.google.com/spreadsheets/d/1oIeG5vg-blm2MZCE-7YhwulUlSz6TOUeY8jAftdP9JE/edit
- [ ] There has been a recent merge up from `develop` (or other base branch)
- [ ] The docs for this branch have been generated and pushed to the doc site (see docs/README.md for details)

## Testing

List the Functional Tests that must be run to confirm this feature

1. ...
2. ...

## Deployment

What deployment considerations are there? (delete any sections you don't need)

### Configuration changes

What configuration changes are included in this PR, and do we need to set specific values for production

### Scripts

What scripts need to be run from the PR (e.g. if this is a report generating feature), and when (once, regularly, etc).

### Migrations

What migrations need to be run to deploy this

### Monitoring

What additional monitoring is required of the application as a result of this feature

### New Infrastructure

What new infrastructure does this PR require (e.g. new services that need to run on the back-end).

### Continuous Integration

What CI changes are required for this

2023-02-21 14:51 UTC, richard-jones requested changes
Can we get an update to one or more of the functional tests to show off the new behaviour?  Can that include one or more test packages to go along with the test.

For example, add another one of these for an upload with multiple journals: https://doaj.github.io/doaj-docs/develop/testbook/index.html#articles_preservation/user_test_script/upload_correctly__structured_file_and_it_is_processed_correctly

2023-02-27 05:03 UTC, RK206 commented
I have updated the functional testcase for multiple journals

2023-02-28 17:04 UTC, richard-jones requested changes
@RK206 I didn't have time to complete the review yet, I will do that asap, but I ran out of time today but there were a couple of changes to request, so I'm submitting this review as is for the moment.

2023-02-28 17:04 UTC, richard-jones commented on doajtest/testbook/articles_preservation/user_test_script.yml
> +    resource: /preservation_upload_test_package/multi_journals.zip
Can we also add an example package resource to the other relevant tests:

https://doaj.github.io/doaj-docs/feature/3424_archiving_project/testbook/index.html#articles_preservation/user_test_script/upload_correctly__structured_file_and_it_is_processed_correctly

https://doaj.github.io/doaj-docs/feature/3424_archiving_project/testbook/index.html#articles_preservation/user_test_script/upload_incorrectly__structured_file

https://doaj.github.io/doaj-docs/feature/3424_archiving_project/testbook/index.html#articles_preservation/user_test_script/upload_correctly__structured_file_with_articles_that_user_do_not_own

2023-03-07 15:02 UTC, RK206 commented
Implemented the changes as suggested

2023-03-09 13:50 UTC, richard-jones commented on doajtest/unit/test_task_preservation.py
> +        self.owner = "rama"
I found the multi-journals test, and I found a couple of bugs in it, so I'm not sure if you were running this locally.  I needed to change "identifier" to "Identifier" in a couple of places, then the test passed.  Looking at the test, though, I still don't know how to confirm if it's testing the multiple packages thing, can you walk me through it?

2023-03-09 13:53 UTC, richard-jones commented on doajtest/testbook/articles_preservation/upload_preservation_files.yml
> +    - Under the label 'UPLOADED PACKAGES', details of the packages that were uploaded are displayed in the format <journal_id>_<Date>.tar.gz
I don't see this, instead I get:

```
Uploaded articles to archive server

Successful articles

article1, article3, article2
```

2023-03-09 13:54 UTC, richard-jones requested changes
There's one common library thing to change (use of `dates.now()`), and a comment about the multi-package unit test.

Otherwise, I am able to run the functional test locally, and it succeeds, but I don't know how to tell whether the uploaded packages are correct in IA, can you add some testing instructions to the PR and/or the functional test to cover how to check what was uploaded to IA?

2023-03-20 11:23 UTC, richard-jones approved these changes
I was able to to successfully test this, and I have pushed a small text update to the functional test to aid the DOAJ team setting up for testing

2023-10-25 08:38 UTC, closed without merging